#pragma once

#include <libopencm3/stm32/gpio.h>

#define GPIO_SW0_PORT GPIOA
#define GPIO_SW0_PIN GPIO0
#define GPIO_SW1_PORT GPIOA
#define GPIO_SW1_PIN GPIO1
#define GPIO_SW2_PORT GPIOA
#define GPIO_SW2_PIN GPIO2
#define GPIO_SW3_PORT GPIOA
#define GPIO_SW3_PIN GPIO0

#define GPIO_A03C_PORT GPIOA
#define GPIO_A03C_PIN GPIO4
#define GPIO_A47C_PORT GPIOA
#define GPIO_A47C_PIN GPIO5
#define GPIO_B03C_PORT GPIOA
#define GPIO_B03C_PIN GPIO6
#define GPIO_B47C_PORT GPIOA
#define GPIO_B47C_PIN GPIO7

#define GPIO_COMBC_PORT GPIOB
#define GPIO_COMBC_PIN GPIO0
#define GPIO_COMB_PORT GPIOB
#define GPIO_COMB_PIN GPIO1
